security:
    jwt:
        expiration-time: 86400000
        secret-key: thisisthesecretkeysupersecretbutnotassecretasitshouldbe
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
